"""Add date to Sport model

Revision ID: 04a1e5d41621
Revises: e574aff2ae9c
Create Date: 2024-11-24 00:09:49.613946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a1e5d41621'
down_revision = 'e574aff2ae9c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=50), nullable=False, server_default='1970-01-01'))
    # ### end Alembic commands ###

    # Set the server default to None
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.alter_column('date', server_default=None)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sport', schema=None) as batch_op:
        batch_op.drop_column('date')
    # ### end Alembic commands ###

